# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.goddancer.com
date_format: "ordinal"
title: Jico
subtitle: "Do what u want to do..."
description: "Do what u want to do..."
keywords: Jico, goddancer
timezone: Asia/Beijing
encoding: "utf-8"
# side_bar_repo_limit: 5
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms: qq,facebook
    # TODO 不蒜子访问统计，待完善
    busuanzi:
        enabled: false
        start_date: 2021-11-11
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: Jico
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/goddancer/rouge-themes
# 去_includes/header.html打开注释应用
highlight_theme: molokai

# ---------------- #
#      Author      #
# ---------------- #
author: Jico
organization: 
organization_url: 
github_username: goddancer
location: Beijing, China
email: goddancer@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 30
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
    - jelyll-gist
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
github: [metadata]
repository: goddancer/goddancer.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: goddancer
    repo: blog-comments
    oauth:
        client_id: 
        client_secret: 
# https://github.com/gitalk/gitalk#install
# my token view here: https://github.com/settings/developers
gitalk:
    owner: goddancer
    repo: blog-comments
    clientID: c7388a652fa81ccd1122
    clientSecret: 70c0c8a2edf97c53f59194b63f5fd0efe3d526bc
# https://utteranc.es/
utterances:
    repo: goddancer/blog-comments
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
# -------------- #
#    exclude     #
# -------------- #
exclude: [packages, node_modules, Gemfile, Gemfile.lock, gems, webpack]
include: [.htaccess, packages/apps]