import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

const Article: NextPage<any> = ({ id, time }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        { id }: { time?.date }
      </main>

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}

export const getStaticProps = async ({ params: { id } }: any) => {
  const res = await fetch('http://localhost:4000/api/time')
  const checkDelete = await fetch(`http://localhost:4000/api/deleted?id=${id}`)
  const deleteData = await checkDelete.json()
  const time = await res.json()
  console.log('time: ', time);
  console.log('deleteData: ', deleteData);
  return {
    props: {
      id: id || null,
      time: time || null,
    },
    revalidate: false,
    notFound: deleteData.deleted,
  }
}

export const getStaticPaths = async (...args: any) => {
  console.log('args2: ', args);
  return {
    paths: [
      {
        params: {
          id: '9', // 这里需要设置默认值，否则初次构建会失败
        },
      }
    ],
    fallback: 'blocking',
  }
}

export default Article